export const GET_PERMITS_LOADING = "GET_PERMITS_LOADING";
export const GET_PERMITS_SUCCESS = "GET_PERMITS_SUCCESS";
export const GET_PERMITS_FAIL = "GET_PERMITS_FAIL";
export const GET_PERMIT_DETAIL_LOADING = "GET_PERMIT_DETAIL_LOADING";
export const GET_PERMIT_DETAIL_SUCCESS = "GET_PERMIT_DETAIL_SUCCESS";
export const GET_PERMIT_DETAIL_FAIL = "GET_PERMIT_DETAIL_FAIL";
